--- 
oauth: 
  request_secret: fzzZhCeb81IbBNRBvO5blWJuNM9CIHSjR3tsicrXU
  request_token: 67898990-HzzhszlZpBVT2AeFY4V7UnaDumpumlcYEVB35C5c
  consumer_secret: d9rPObKZ5Z9axPHNZe2KdUszKs7FfOAw61JQg2KaA
  consumer_key: j5L0vJaEgGPx7bKE17knw
update_every: 5
basic_auth: 
  user: hkitevent
  password: r0rcr4ft
auth_mode: oauth
ical_url: "http://www.google.com/calendar/ical/s7v0ntq98kbmvp4hafbpvl2qkc%40group.calendar.google.com/public/basic.ics"
